name: Cypress Automation CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Ensures the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '20'  # Use Node.js 20 as per the latest requirements

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run --spec "cypress/e2e/API-Automation/**/*"  # Adjust path if necessary

      - name: Upload Test Artifacts
        if: failure()  # Only upload if tests fail
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: cypress-artifacts
          path: cypress/screenshots/  # Directory for screenshots of failed tests
