name: API automation run on dev env
on:
  pull_request:
    types: [ opened, edited, synchronize ]
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  api-run:
    runs-on: ubuntu-latest
    name: API Automation Tests
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Delete cypress directory (screenshots)
        shell: bash
        run: |
          echo "delete Screenshots directory"
          rm -rf cypress/screenshots || true
      - name: Install dependencies
        shell: bash
        run: |
          npm install
      - name: List directories
        shell: bash
        run: |
          echo "list base directory"
          ls -la
          echo "list cypress directory"
          ls -ls cypress
          echo "npx version"
          npx --version
          echo "To remove ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported."
          export LIBGL_DRI3_DISABLE=1
      - name: Run api tests
        run: |
          npx cypress run --spec cypress/e2e/api/tests/
      - name: Publish test summary results
        if: always()
        run: npx github-actions-ctrf ctrf/ctrf-report.json
