name: API automation run on dev env
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  api-run:
    runs-on: ubuntu-latest
    name: API Automation Tests
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Delete Cypress directory (screenshots)
        run: |
          echo "Deleting screenshots directory"
          rm -rf cypress/screenshots || true
      - name: Install dependencies
        run: npm install
      - name: List directories
        run: |
          echo "Listing base directory"
          ls -la
          echo "Listing Cypress directory"
          ls -ls cypress
          echo "npx version"
          npx --version
          echo "Disabling GPU memory buffer support to prevent errors"
          export LIBGL_DRI3_DISABLE=1
      - name: Run API tests
        run: npx cypress run --spec cypress/e2e/API-Automation/
      - name: Publish test summary results
        if: always()
        run: npx github-actions-ctrf --output-file ctrf/ctrf-report.json || true
