name: API automation run on dev env
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  api-run:
    runs-on: ubuntu-latest
    name: API Automation Tests
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Delete Cypress screenshots directory
        run: |
          echo "Deleting screenshots directory if it exists"
          rm -rf cypress/screenshots || true

      - name: Install dependencies
        run: npm install

      - name: Check base directory structure
        run: |
          echo "Listing base directory"
          ls -la
          echo "Listing Cypress directory structure"
          ls -la cypress
          echo "Listing API-Automation directory structure"
          ls -la cypress/e2e/API-Automation || echo "Directory not found"

      - name: Run API tests
        run: npx cypress run --spec cypress/e2e/API-Automation/ --headed --browser chrome

      - name: Publish test summary results
        if: always()
        run: npx github-actions-ctrf --output-file ctrf/ctrf-report.json || true
