name: Cypress Automation CI

on:
  pull_request:
    branches: [main]  # Run on PRs to the main branch
  push:
    branches: [main]  # Run on code pushes to the main branch
  workflow_dispatch:  # Allow manual run of the workflow

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run --spec cypress/e2e/API-Automation/

      - name: Upload Test Artifacts
        if: failure()  # Only upload screenshots/videos if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/screenshots/  # Upload screenshots for failed tests

      - name: Publish Test Report (Optional)
        run: npx cypress run --reporter junit
        env:
          # Set any additional environment variables needed here
          BASE_URL: 'https://api-singapore.bugraid.ai/api/v1'  # If your tests need a specific BASE_URL
